version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
  dashboard:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    command: streamlit run dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - backend
